on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - uses: ./
      - name: Commit files
        run: |
          git status
          git config --local user.name "tuckerlong"
          git commit -m "Auto updating data.json" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main